services:
  proxy:
    container_name: ecommerce-proxy
    image: traefik:v3.6
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:main-814c1c6
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  # service that recieves the traces
  alloy:
    container_name: traces-service
    image: grafana/alloy:v1.3.1
    volumes:
      - ./logs/config/config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  # service that saves the tracers
  tempo:
    container_name: tempo-service
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./logs/config/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200" # tempo
      - "4317" # otlp grpc
    depends_on:
      - init

  prometheus:
    container_name: prometheus-service
    image: prom/prometheus:v3.4.0
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./logs/config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    container_name: logs-dashboard
    image: grafana/grafana:11.5.2
    volumes:
      - ./logs/config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_INSTALL_PLUGINS=grafana-exploretraces-app  ## plugin...
    ports:
      - "3000:3000"

  redis:
    image: redis:7.4
    container_name: secrets-storage
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  mysql:
    container_name: ecomerce-database
    image: mysql:8.0
    env_file:
      - ./db/.env
    volumes:
      - ecommerce-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    env_file:
      - ./db/.env
    labels:
      traefik.http.routers.phpmyadmin.rule: Host(`db.localhost`)
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80

  mailhog:
    container_name: ecommerce-smtp-server
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: "none"
    labels:
      traefik.http.routers.mailhog.rule: Host(`email.localhost`)
      traefik.http.services.mailhog.loadbalancer.server.port: 8025

  bucket:
    container_name: ecommerce-bucket
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    volumes:
      - bucket_storage:/data
    labels:
      traefik.http.routers.bucket.rule: Host(`bucket.localhost`)
      traefik.http.routers.bucket.service: bucket-service
      traefik.http.services.bucket-service.loadbalancer.server.port: 9001
      traefik.http.routers.minio-api.rule: Host(`images.localhost`)
      traefik.http.routers.minio-api.service: minio-api-svc
      traefik.http.services.minio-api-svc.loadbalancer.server.port: 9000

  backend:
    container_name: go-ecommerce-api
    env_file:
     - ./backend/.env
    develop:
      watch:
        - path: ./backend/
          action: rebuild
          target: ./api
    build:
      context: ./
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      traefik.http.routers.backend.rule: Host(`api.localhost`)
      traefik.http.services.backend.loadbalancer.server.port: 4321

volumes:
  ecommerce-mysql-data:
  bucket_storage:
  redis_data:
    driver: local
