services:
  proxy:
    container_name: ecommerce-proxy
    image: traefik:v3.6
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    container_name: ecomerce-database
    image: mysql:8.0
    env_file:
      - ./db/.env
    volumes:
      - ecommerce-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    env_file:
      - ./db/.env
    labels:
      traefik.http.routers.phpmyadmin.rule: Host(`db.localhost`)
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80

  mailhog:
    container_name: ecommerce-smtp-server
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: "none"
    labels:
      traefik.http.routers.mailhog.rule: Host(`email.localhost`)
      traefik.http.services.mailhog.loadbalancer.server.port: 8025

  bucket:
    container_name: ecommerce-bucket
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - ./.env
    volumes:
      - bucket_storage:/data
    labels:
      traefik.http.routers.bucket.rule: Host(`bucket.localhost`)
      traefik.http.routers.bucket.service: bucket-service
      traefik.http.services.bucket-service.loadbalancer.server.port: 9001
      traefik.http.routers.minio-api.rule: Host(`images.localhost`)
      traefik.http.routers.minio-api.service: minio-api-svc
      traefik.http.services.minio-api-svc.loadbalancer.server.port: 9000

  backend:
    container_name: go-ecommerce-api
    env_file:
     - ./backend/.env
    develop:
      watch:
        - path: ./backend/
          action: rebuild
          target: ./api
    build:
      context: ./
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      traefik.http.routers.backend.rule: Host(`api.localhost`)
      traefik.http.services.backend.loadbalancer.server.port: 4321

volumes:
  ecommerce-mysql-data:
  bucket_storage:
